import os
import json
import asyncio
from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List
from openai import AsyncOpenAI
from supabase import create_client, Client
from dotenv import load_dotenv

# 1. Load Secrets
load_dotenv()

app = FastAPI(title="IkigAI Nexus API")

# 2. CORS (Allow Frontend to talk to Backend)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 3. Initialize Clients
url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_SERVICE_KEY")
supabase: Client = create_client(url, key)

openai_client = AsyncOpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

# --- Models ---
class Message(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    messages: List[Message]
    user_id: str  # We need to know WHO is talking

# --- Helper: Save to DB ---
async def save_message(user_id: str, role: str, content: str):
    try:
        supabase.table("chat_messages").insert({
            "user_id": user_id,
            "role": role,
            "content": content
        }).execute()
    except Exception as e:
        print(f"Error saving message: {e}")

# --- Endpoints ---

@app.get("/health")
def health_check():
    return {"status": "active"}

TEST_MODE = True

@app.post("/chat")
async def chat_endpoint(request: ChatRequest):
    # 1. Get the latest user message (the last one in the list)
    latest_msg = request.messages[-1]
    
    # 2. Save User Message to DB (Fire and forget)
    asyncio.create_task(save_message(request.user_id, "user", latest_msg.content))

    if TEST_MODE:
        async def mock_stream():
            fake_response = "This is a test response. In production, this will be generated by OpenAI."

            for word in fake_response.split():
                yield word + " "
                await asyncio.sleep(0.1)
            
            asyncio.create_task(save_message(request.user_id, "assistant", fake_response))
        
        return StreamingResponse(mock_stream(), media_type="text/plain")
    
    # 3. Define the System Personality
    system_prompt = {
        "role": "system",
        "content": """You are an empathetic, insightful career coach helping the user find their Ikigai. 
        Your goal is to uncover 4 things:
        1. Passion (What they love)
        2. Mission (What the world needs)
        3. Vocation (What they can be paid for)
        4. Profession (What they are good at)
        
        Do NOT lecture them. Ask probing questions. Keep responses concise and conversational."""
    }

    # 4. Prepare the conversation for OpenAI
    # We take the last 10 messages to save tokens, plus the system prompt
    final_messages = [system_prompt] + [msg.model_dump() for msg in request.messages[-10:]]

    # 5. The Streaming Generator
    async def generate_stream():
        full_response = ""
        
        try:
            stream = await openai_client.chat.completions.create(
                model="gpt-4o-mini", # Or "gpt-3.5-turbo" to save money
                messages=final_messages,
                stream=True
            )

            async for chunk in stream:
                if chunk.choices[0].delta.content:
                    text = chunk.choices[0].delta.content
                    full_response += text
                    yield text # Send to frontend immediately

            # 6. Save AI Response to DB (After stream finishes)
            asyncio.create_task(save_message(request.user_id, "assistant", full_response))

        except Exception as e:
            yield f"Error: {str(e)}"

    return StreamingResponse(generate_stream(), media_type="text/plain")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)