import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Averia_Serif_Libre, Overlock } from "next/font/google";
import { Navbar } from "@/components/navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const asLibre = Averia_Serif_Libre({
  weight: ["300", "400", "700"],
  variable: "--font-averia-serif-libre",
  subsets: ["latin"],
});

const overlock = Overlock({
  weight: ["400", "700"],
  variable: "--font-overlock",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${asLibre.variable} ${overlock.variable} font-sans antialiased`}
      >
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
